In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
d1 = np.array([1,2,3,4,5])

In [4]:
d1

array([1, 2, 3, 4, 5])

In [5]:
np.ndim(d1)

1

In [6]:
d2 = np.array([[1,2,3],[10,20,30]])

In [7]:
d2

array([[ 1,  2,  3],
       [10, 20, 30]])

In [8]:
np.ndim(d2)

2

In [9]:
import time

# python list

l1 = list(range(1,50000001))

start = time.time()

l2 = [i*2 for i in l1]

print('Time taken', time.time() - start )


Time taken 33.60951638221741


In [11]:
arr = np.array(range(1,50000001))

start = time.time()

arr2 = arr * 2

print('Time taken', time.time() - start )


Time taken 0.7187955379486084


In [12]:
import numpy as np

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.zeros((3,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
np.ones((3,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
import pandas as pd

In [21]:
d={'name':['a','b','c'],'age':[2,3,4]}

In [22]:
d

{'name': ['a', 'b', 'c'], 'age': [2, 3, 4]}

In [24]:
pd.DataFrame(d)

,name,age
0,a,2
1,b,3
2,c,4


In [25]:
st_data=pd.DataFrame(d)

In [26]:
st_data.to_csv('st data.csv')